name: Integration Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        # ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Run Clippy
        run: cargo clippy -- -D warnings

      - name: Install SQLite on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y sqlite3 libmagic-dev

      - name: Install SQLite on macOS
        if: matrix.os == 'macos-latest'
        run: brew install sqlite3 libmagic file

      - name: Install SQLite on Windows
        if: matrix.os == 'windows-latest'
        run: choco install sqlite

      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo test --verbose
