name: Integration Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install SQLite on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y sqlite3

      - name: Install SQLite on macOS
        if: matrix.os == 'macos-latest'
        run: brew install sqlite3

      - name: Install SQLite on Windows
        if: matrix.os == 'windows-latest'
        run: choco install sqlite

      - name: Build program
        run: cargo build --release

      - name: Run integration test
        run: cargo test --test integration -- --nocapture
